### ISSUE TITLE
The telegram bridge is not working

### ISSUE THREAD

**Issue by says112** [mautrix/docs#72]
The telegram bridge does not start. Logs:

[2024-08-29 21:00:23,186] [DEBUG@mau.as.api.bot] req #74: GET https://line.alexnetwork.space/_matrix/client/versions?user_id=@telegrambot:line.alexnetwork.space None
[2024-08-29 21:00:23,190] [DEBUG@mau.as.api.bot] req #74 (/versions) completed in 4.3ms with status 401
[2024-08-29 21:00:23,190] [ERROR@mau.mx] Connection to homeserver failed, retrying in 10 seconds
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mautrix/bridge/matrix.py", line 226, in wait_for_connection
    self.versions = await self.az.intent.versions()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/client/api/base.py", line 118, in versions
    resp = await self.api.request(Method.GET, Path.versions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 425, in request
    resp_data, resp = await self._send(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 265, in _send
    raise make_request_error(
mautrix.errors.request.MUnknownToken: Invalid access token passed.
root@best-line:/opt/matrix#

**Comment by tulir** [comment]
This is not the place for issues with bridges. Also, only actual bugs should be reported on GitHub. The Matrix rooms (linked in the docs and bridge readmes) should be used for help with setup issues that are caused by user error.
